# Generated by Django 4.0.5 on 2022-07-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_alter_user_rpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Rpassword',
        ),
    ]
